[PIPELINE] Bump clang-tidy-aarch64 job timeout from 1 hour to 3 hours
Background
----------
* Occasionally I have seen the `clang-tidy-aarch64` job time out. Particularly when multiple
  MRs get merged in quick succession in the YDB project.

Issue
-----
* For example, a5d73c19, 6f93b5a5 and de7e325c were all merged in quick succession today and
  the following job failure happened.

  https://gitlab.com/YottaDB/DB/YDB/-/jobs/6109073587

  **clang-tidy-aarch64**
  ```
  The script exceeded the maximum execution time set for the job
  .
  .
  ERROR: Job failed: script timeout context: context deadline exceeded
  ```

* This is because the `clang-tidy-aarch64` job runs when each MR gets merged into master. And
  so each of the jobs corresponding to the multiple commits load up the gitlab runner host enough
  that they each end up taking more than 1 hour to run. And get timed out and fail.

Fix
---
* The timeout for the `clang-tidy-aarch64` job is bumped from the 1 hour default to 3 hours and
  it is hoped that this should avoid failures like the above even if multiple merges happen
  in quick succession.