[#1018] [V71001] Fix Release build failure with gcc due to -Werror=uninitialized
* The RelWithDebInfo/Release build failed when run with `gcc` as the compiler (the build
  runs fine with `clang` as the compiler).

* Below was the error while linking `libyottadb.so`.

  ```c
  In function 'push_mval',
      inlined from 'mu_upgrd_dngrd_confirmed' at sr_port/mu_upgrd_dngrd_confirmed.c:40:15:
  sr_port/push_mval.c:28:39: error: 'dummy' is used uninitialized [-Werror=uninitialized]
     28 |         mv_chain->mv_st_cont.mvs_mval = *arg1;
        |                                       ^
  sr_port/mu_upgrd_dngrd_confirmed.c: In function 'mu_upgrd_dngrd_confirmed':
  sr_port/mu_upgrd_dngrd_confirmed.c:35:25: note: 'dummy' declared here
     35 |         mval            dummy, *input_line;
        |                         ^
  lto1: all warnings being treated as errors
  ```

* This error showed up because GT.M V7.1-001 added `-Werror` to the `CMAKE_C_FLAGS` in
  `CMakeLists.txt`,

* While it is true that `dummy` is used uninitialized in line 28 of `push_mval.c` above,
  that usage is okay because it is later initialized in a call to `op_read.c` (in
  `sr_port/mu_upgrd_dngrd_confirmed.c`). Therefore, there is no real issue here.

* But to fix this build error, the `dummy` mval is zero initialized as part of this commit.