[#1059] [V71003] Fix build error in patstr.c during debug builds
Issue
-----
* GT.M added several `free_alts(&init_alt)` calls to free allocated alternation memory before every
  return path in `sr_port/patstr.c`, including at the end of the `patstr()` function outside of the
  `for` loop. The `patstr()` function returns an `int`, and the addition of the `free_alts(&init_alt)`
  at the end of the function outside the `for` loop, caused an error during CMake Debug builds, but
  not during RelWithDebInfo builds.

  ```
  sr_port/patstr.c:940:1: error: control reaches end of non-void function [-Werror=return-type]
    940 | }
        | ^
  ```

Fix
---
* A `return 0;` was added after the `free_alts()` call at the end of the `patstr()` function in order
  to fix debug builds.