Install libclang and cargo from stable, not testing
This fixes the following pipeline error:

```
Processing triggers for libc-bin (2.31-4) ...
E: Could not configure 'libc6:amd64'.
E: Could not perform immediate configuration on 'libnss-nis:amd64'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
```

It's unclear to me why this problem occurs and why it only started
happening recently. However, since this change no longer installs libc
from the testing repo, I expect the problem will not reoccur.

The reason these were originally installed from testing is because
libclang-10-dev was not available on stable. However, it turns out that
clang-10 is not strictly necessary and clang-7 will work just as well.

This also installs `clang` instead of `libclang-dev`, fixing the following
error while building YDBRust:

```
$ cargo check
--- stderr
/usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found
/usr/include/x86_64-linux-gnu/sys/types.h:144:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/libcore/result.rs:1188:5
```

The failure I've seen before and happens because clang can't find the
appropriate header files for the compiler. However, I'm not entirely
sure why it worked before. Since the fix is simple and easy to maintain,
I don't plan to look into this further.

`--no-install-recommends` is not strictly required for the fix, but is
good practice since it decreases the size of the final docker image.