Fix AARCH64 Debian 12 build failure due to -ggdb3 in CMAKE_ASM_FLAGS_DEBUG
Background
----------
* In a Debian 12 in-house AARCH64 system, we noticed the YottaDB Debug build fail when it used GCC
  as the compiler. It worked fine when CLANG was used. The failure symptom was the following.

  ```
  Fatal error: unknown option `-ggdb3'
  ```

Issue
-----
* In a Debian 11 AARCH64 system, the following `as -ggdb3` command works without errors.

  **Debian 11**
  ```sh
  $ gcc --version | head -1
  gcc (Debian 10.2.1-6) 10.2.1 20210110

  $ as --version
  GNU assembler (GNU Binutils for Debian) 2.35.2

  $ as -ggdb3 < /dev/null

  ```

* But the same command fails in a Debian 12 AARCH64 system.

  **Debian 12**
  ```sh
  $ gcc --version | head -1
  gcc (Debian 12.2.0-14) 12.2.0

  $ as --version
  GNU assembler (GNU Binutils for Debian) 2.40

  $ as -ggdb3 < /dev/null
  Assembler messages:
  Fatal error: unknown option `-ggdb3'
  ```

* So looks like support for `-ggdb3` was removed between `as 2.35.2` and `as 2.40`. Not sure why.

Fix
---
* It is not clear why the `-ggdb3` option is passed to the assembler in case of a Debug build on AARCH64.
  The build seems to run fine even without that flag and since it is only the Debug build that is going to
  be affected (if at all), this commit removes this option (from the `CMAKE_ASM_FLAGS_DEBUG` variable
  in `sr_linux/platform.cmake`) in case of `aarch64`.