Fix AARCH64 build failures due to removal of -Wno-parentheses
* Commit 44075cc8 removed `-Wno-parentheses` from the compiler flags. It ensured `x86_64` systems
  build fine. But `aarch64` systems had the following build errors/warnings after that change.

  ```
  /tmp/yottadb-src/sr_aarch64/find_line_call.c: In function 'find_line_call':
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:44:46: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
     44 | #define PUSH_NUM_LIT3   (AARCH64_INS_MOV_REG & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20))
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:82:17: note: in expansion of macro 'PUSH_NUM_LIT3'
     82 |             || (PUSH_NUM_LIT3 == (*call_addr & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20)))
        |                 ^~~~~~~~~~~~~
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:48:46: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
     48 | #define PUSH_NUM_LIT7   (AARCH64_INS_LSR     & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20))
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:86:17: note: in expansion of macro 'PUSH_NUM_LIT7'
     86 |             || (PUSH_NUM_LIT7 == (*call_addr & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20))))
        |                 ^~~~~~~~~~~~~
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:44:46: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
     44 | #define PUSH_NUM_LIT3   (AARCH64_INS_MOV_REG & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20))
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:91:29: note: in expansion of macro 'PUSH_NUM_LIT3'
     91 |                         || (PUSH_NUM_LIT3 == (*call_addr & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20)))
        |                             ^~~~~~~~~~~~~
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:48:46: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
     48 | #define PUSH_NUM_LIT7   (AARCH64_INS_LSR     & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20))
  /tmp/yottadb-src/sr_aarch64/find_line_call.c:95:29: note: in expansion of macro 'PUSH_NUM_LIT7'
     95 |                         || (PUSH_NUM_LIT7 == (*call_addr & (AARCH64_MASK_OP_12 << AARCH64_SHIFT_OP_20))))
        |                             ^~~~~~~~~~~~~
  ```

* This commit fixes the above warnings/errors by adding the needed surrounding parentheses.