[DEBUG-ONLY] Fix assert failure about TREF(stapi_errstr) in YDBRust invalid_exit subtest
* In the YDBRust repo, running the `invalid_exit` subtest caused the following assert failure.

```rust
$ cargo test --test invalid_exit
   Compiling yottadb v0.3.0 (/home/nars/work/github/YDBRust)
    Finished test [unoptimized + debuginfo] target(s) in 7.41s
     Running target/debug/deps/invalid_exit-a456ff038c1c3fba

running 1 test
%YDB-F-ASSERT, Assert failed in sr_unix/libyottadb_int.h line 1010 for expression (ERRSTR == TREF(stapi_errstr))
error: test failed, to rerun pass '--test invalid_exit'
```

* In this test case, `ydb_ci_t()` invokes an M program that in turn invokes a C external call that
  does a `ydb_exit()` call. This is expected to issue a `YDB_ERR_INVYDBEXIT` error.

* The assert failure happened because the global variable `TREF(stapi_errstr)` got changed when
  `ydb_exit()` did a call to `threaded_api_ydb_engine_lock()` but did not get reset when it called
  `threaded_api_ydb_engine_unlock()`. This is because `RELEASE_LOCK` parameter was FALSE. This is because
  we are already inside a `ydb_ci_t()` call.

  Not doing this reset caused problems when `ydb_ci_t()` called the `threaded_api_ydb_engine_unlock()`
  function and failed the assert.

* This is fixed by moving the `TREF(stapi_errstr)` reset logic outside the `if (RELEASE_LOCK)` block.
  This ensures we do the reset whether `RELEASE_LOCK` is TRUE or FALSE (the FALSE case is the one
  which is being fixed in this commit).