[Pipeline] Fix Rocky Linux pipeline due to missing gzip
Rocky Linux was bumped to v8.6 yesterday
(https://rockylinux.org/news/rocky-linux-8-6-ga-release/); as a result,
its docker image has changed. Seems they removed the gzip package.

The error in the pipeline
(https://gitlab.com/bradwesthafer/YDB/-/jobs/2469547544) is:

```
Utility [gzip] is needed by ydbinstall.sh but not found. Exiting.
ERROR: executor failed running [/bin/sh -c cp -R /tmp/staging /tmp/ydb-release &&     yum update -y &&     yum install -y                     file                     binutils                     findutils                     elfutils-libelf                     libicu                     wget                     procps-ng 		    nano 		    &&     /tmp/ydb-release/ydbinstall --utf8 default --installdir /opt/yottadb/current &&     yum remove -y wget &&     yum clean all &&     rm -rf /var/cache/yum &&     rm -rf /tmp/ydb-release]: exit code: 1
```

To resolve, install gzip.