[#1000] [V71000] Revive nixed DBFILERDONLY error as it is needed in new places by GT.M V7.1-000
* While building GT.M V7.1-000, I noticed a build failure with the following errors.

  ```c
  /Distrib/YottaDB/V998_R203/sr_port/mm_read.c:104:46: error: use of undeclared identifier 'ERR_DBFILERDONLY'
                  rts_error_csa(CSA_ARG(csa) VARLSTCNT(10) ERR_DBFILERDONLY, 3, DB_LEN_STR(gv_cur_region), 0,
                                                           ^
  /Distrib/YottaDB/V998_R203/sr_port/mm_read.c:134:46: error: use of undeclared identifier 'ERR_DBFILERDONLY'
                  rts_error_csa(CSA_ARG(csa) VARLSTCNT(10) ERR_DBFILERDONLY, 3, DB_LEN_STR(gv_cur_region), 0,
                                                           ^
  ```

* The `DBFILERDONLY` error exists in the GT.M side but was nixed in the YottaDB side in commit 7422ced8
  as there was no use of this then.

* But GT.M V7.1-000 introduced a couple of new usages of this error in `sr_port/mm_read.c`. And this usage
  was valid and so this commit revives the DBFILERDONLY error message back again in the YottaDB side.