[#1018] [V71001] Fix build failure due to silent merge conflicts
When I attempted a YottaDB build with the previous V7.1-001 merge commits, I got a failure
with the below types of errors.

Error 1
--------
* `aligned_source_buffer` is an int4 array but GT.M had added a GBLREF line without the `[]`. And this
  is what caused the below error. Fixed by adding a `[]`.

  ```c
  sr_port/op_commarg.c:38:33: error: conflicting types for 'aligned_source_buffer'; have 'int4' {aka 'int'}
  ```

* Next type of errors were the following.

  ```c
  sr_unix/iottdef.h:22:10: fatal error: setterm.h: No such file or directory
  sr_unix/suspend.c:58:17: error: implicit declaration of function 'setterm' [-Werror=implicit-function-declaration]
  ```

  This was because GT.M had renamed `setterm.h` to `iott_setterm.h`. And all usages of
  setterm()/resetterm() with iott_setterm()/iott_resetterm().

  The above change was incorporated in all YottaDB files including the above files that got errors.
  I also made this change in all files where the words setterm or resetterm were used in comments.

* Next encountered errors were the following.

  ```c
  sr_port/op_fnzysuffix.c:43:9: error: implicit declaration of function 'MurmurHash3_x64_128'; did you mean 'MurmurHash3_x86_32'? [-Werror=implicit-function-declaration]
  sr_unix/op_fnzyhash.c:42:9: error: implicit declaration of function 'MurmurHash3_x64_128'; did you mean 'MurmurHash3_x86_32'? [-Werror=implicit-function-declaration]
  ```

  This is because the function `MurmurHash3_x64_128()` was removed in GT.M V7.1-001. It is likely
  because they don't need it but YottaDB needed it as can be seen by the above 2 errors.

  Therefore, I restored the master branch copy of the following files as part of this commit.
  That automatically fixed the above build errors.
  - sr_unix/mmrhash.c
  - sr_unix/mmrhash.h

* The last type of error was the following.

  ```c
  sr_unix/gtmsecshr.c:623:2: error: use of undeclared identifier 'gtm_white_box_test_case_enabled'; did you mean 'ydb_white_box_test_case_enabled'?
  ```

  This is because of white-box code added to gtmsecshr.c as part of GT.M V7.1-001. The commit message
  of a prior commit 4797c618 described a similar change in `sr_unix/gtmsecshr_wrapper.c` and why it
  was not a good idea and removed GT.M V7.1-001 change from that file. Therefore, decided to do the
  same thing to `gtmsecshr.c` as well and so removed all white-box related and debug code added for
  that purpose from this file.