[YottaDB/Lang/YDBPython#32] Exit with negative (not positive) status for SIGTERM/SIGINT/SIGQUIT on Simple API application
Background
----------
* The YDBPython project pipeline failed in the `test_fatal_signal` test with the following symptom
  after ae2721d8 was merged.

  ```sh
  $ cd YDBPython
  $ python -m pytest -k test_fatal_signal

  tests/test_fatal_signal.py .F                                                                                        [100%]
  .
  .
  >       assert p.exitcode == exit_code
  E       AssertionError: assert 15 == 241
  E        +  where 15 = <Process name='Process-17' pid=41173 parent=41149 stopped exitcode=15>.exitcode

  tests/test_fatal_signal.py:51: AssertionError
  ================================================= short test summary info ==================================================
  FAILED tests/test_fatal_signal.py::test_fatal_signal - AssertionError: assert 15 == 241
  ```

Issue
-----
* The test sends a SIG-15 and expects the process to exit with an exit code of `-15` (i.e. `256 - 15` = `241`).
  But instead, it exits with a code of `15`.

* The issue is that before ae2721d8, the following logic would kick in and terminate the process on receipt
  of a fatal signal (like SIG-15/SIGTERM). Notice the `-` in the `-exi_condition`. This means, we would exit
  with `-15` in case of a SIG-15 etc.

  **sr_unix/signal_exit_handler.c**
  ```c
    133         EXIT(-exi_condition);
  ```

* But with the changes in ae2721d8, the same process would exit using the below code path. Notice we exit
  using `sig`. No `-` sign. And because of this, a SIG-15 would terminate the process with an exit code of `15`.

  **sr_unix/signal_exit_handler.c**
  ```c
     69                                 UNDERSCORE_EXIT(sig);
  ```

* And this difference is what caused the YDBPython pipeline failure.

Fix
---
* To keep things consistent, `sr_unix/signal_exit_handler.c` is fixed to exit with `-sig` (negative value of
  signal number).

* While at this, noticed a similar inconsistent usage in `sr_unix/generic_signal_handler.c` (a rarely used
  code path) so fixed that too to exit with the negative value of the signal number.