[#590] Add git commit to CMake release stamp
This will be updated whenever `make` is run and the git commit has
changed. Example output:

```
$ ./yottadb -dir <<< 'zwr $ZRELDATE'

YDB>
$ZRELDATE="20200624 12:02 b03d4520 (dirty)"
```

- Add git to dockerfile
- Don't rename release_name.h

Since the preprocessed file is output to a different directory, there is
no need to change the name. This makes rebasing over upstream GT.M
changes much easier.

- Update example release stamp
- Update dependencies in CMake
- Use different file for YDB_RELEASE_STAMP to work around dependency issues

Although CMake will regenerate the files properly if they are named the
same (for instance: `sr_linux/release_name.h` and `build/release_name.h`),
they will not be handled correctly by the preprocessor. Trying to put
`#define YDB_RELEASE_STAMP      "@YDB_RELEASE_STAMP@"` directly in
`sr_linux/release_name.h` led to the build file being regenerated every
time the commit changed, but also lead to `YDB_RELEASE_STAMP` being
defined as the literal string `@YDB_RELEASE_STAMP@`. My belief is that
the preprocessor was using the file in the same directory as the source
files instead of the file in the build directory.

To work around this, a new file is introduced which is not present in
the source directory. This forces the preprocessor to look in the build
directory instead.

- Use `--short` for git commit
- Add git to debian install
- Use cmake3 on centos

This avoids strange dependency issues when generating the git commit.

- Use find_program instead of find_package

This avoids the following CentOS-only issue:

```
CMake Error at CMakeLists.txt:416 (target_link_libraries):
  IMPORTED library can only be used with the INTERFACE keyword of
  target_link_libraries
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindGit.cmake:90 (add_executable)
  cmake/git-watcher.cmake:71 (find_package)
  CMakeLists.txt:1006 (include)
```

- Don't set `GIT_NOTFOUND` in $ZRELDATE if git wasn't found

Before:
```
YDB>zwr $ZRELDATE
$ZRELDATE="20200625 20:50 GIT-NOTFOUND"
```

After:
```
YDB>zwr $ZRELDATE
$ZRELDATE="20200625 21:02  "
```

- Add a warning with debug information if git failed to report status
- Make check_git_repository a dependency of libyottadb and libmumps directly

Previously it was a dependency of the yottadb executable, which meant
code duplication and also prevented building `libyottadb` without also
building the executable.

I also tried making it a dependency of libyottadb only, but that led to
the following intermittent dependency issue:

```
In file included from /tmp/yottadb-src/sr_x86_64/obj_filesp.c:56:
/tmp/yottadb-src/sr_linux/release_name.h:29:11: fatal error: release_commit.h: No such file or directory
 # include "release_commit.h"
           ^~~~~~~~~~~~~~~~~~
```

- Add instructions for installing cmake3