[#1027] [V71002] Fix build failure in sr_unix/gv_trigger.c due to [-Werror=vla]
* After resolving all conflicts (during the GT.M V7.1-002 merge), attempting a build showed the
  following error.

  ```c
  sr_unix/gv_trigger.c: In function 'gvtr_process_range':
  sr_unix/gv_trigger.c:521:25: error: ISO C90 forbids variable length array 'new_elem_block' [-Werror=vla]
    521 |                         ASSIGN_GVTR_SUBS_RANGE_KEYS(len,gvtr_subs_point.subs_key);
        |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  sr_unix/gv_trigger.c:532:33: error: ISO C90 forbids variable length array 'new_elem_block' [-Werror=vla]
    532 |                                 ASSIGN_GVTR_SUBS_RANGE_KEYS(len,gvtr_subs_range.subs_key1);
        |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  sr_unix/gv_trigger.c:546:33: error: ISO C90 forbids variable length array 'new_elem_block' [-Werror=vla]
    546 |                                 ASSIGN_GVTR_SUBS_RANGE_KEYS(len,gvtr_subs_range.subs_key2);
        |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```

* This is due to new `variable length array` usages in the above file in GT.M V7.1-002.

* Variable length arrays are best avoided and so YottaDB has always removed any vla usages in GT.M code
  before merging it in (see commit 1b80e817 for example).

* In this case, the vla usage seems to have been added for some SCA (Static Code Analyzer) that the
  GT.M development environment uses internally.

* I don't see the need for that at all so removed it as part of this commit.

* I did keep the new `ASSIGN_GVTR_SUBS_RANGE_KEYS` macro as it avoided code duplication in 3 places.
  But I did enhance its interface to pass 2 more parameters as they were being silently used inside
  the macro without being explicitly passed as parameters.