[YottaDB/DBMS/YDBOcto#646, YottaDB/DBMS/YDBOcto#641] Incorporate git-watcher changes from YDBOcto to upstream YDB repo
- Add license of original author
- Add a dependency on the git index for `check_git_repository`. This
  allows not rerunning the target on each `make` invocation.
- Set the git directory properly in docker images

  Previously, .git couldn't be found at configure time because `cmake` was
  run in a different directory than the git repo. It's needed at
  configure time to set the dependency on the git index.

- Use `custom_command` instead of `custom_target` so it doesn't have to
  be rerun each time make is called.

  The diffence between this and adding the dependency on the git index
  is that adding `.git/index` tells cmake it *needs* to rerun the
  command on each change to the index; this tells cmake not to run it at
  any other time.

- Use find_executable instead of find_package, because find_package is broken with `ninja`:

  ```
  CMake Error at CMakeLists.txt:417 (target_link_libraries):
    IMPORTED library can only be used with the INTERFACE keyword of
    target_link_libraries
  Call Stack (most recent call first):
    /usr/share/cmake-3.16/Modules/FindGit.cmake:90 (add_executable)
    cmake/git-watcher.cmake:101 (find_package)
    CMakeLists.txt:1009 (include)
  ```

- Add a custom_target that does nothing but depend on release_commit.h

  Without the custom target, this gave an error when building for the first time:

  ```
  In file included from /home/joshua/src/yottadb/YDB/sr_x86_64/obj_filesp.c:56:
  /home/joshua/src/yottadb/YDB/sr_linux/release_name.h:29:11: fatal error: release_commit.h: No such file or directory
     29 | # include "release_commit.h"
        |           ^~~~~~~~~~~~~~~~~~
  ```

  That happened because there was no explicit dependency between
  `release_name.h` and `release_commit.h`. I couldn't find an easy way
  to add one (I tried `OBJECT_DEPENDS` and it didn't work), so instead
  this adds the dependency to the whole `libmumps` target, so that
  `release_commit.h` will be built before starting on any of the files for
  the libmumps target.

  Note that targets cannot depend on files directly, only on other
  targets: <https://cmake.org/pipermail/cmake/2010-March/035621.html>