[YDBDoc#279] Fix Rust Version in Debian Image (& misc changes)
Rust v1.48 (installed from apt in Debian 11) fails as follows when running say_hello_rust:

```
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/mod.rs:29:20
   |
29 |     pub(crate) use std::hint::spin_loop;
   |                    ^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error[E0658]: use of unstable library feature 'renamed_spin_loop'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/mod.rs:100:9
    |
100 |         std::hint::spin_loop();
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error[E0658]: use of unstable library feature 'renamed_spin_loop'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/sync/task/atomic_waker.rs:285:17
    |
285 |                 hint::spin_loop();
    |                 ^^^^^^^^^^^^^^^
    |
    = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `tokio`.

To learn more, run the command again with --verbose.
error: build failed
```

Checking our YDBRust pipeline, our pipeline uses the stable version of
Rust (currently v1.59) to run its code.

Therefore, I changed this Debian image to install the stable version of
Rust.

Misc changes:
- Remove locales package, and remove US locale. We already use the
C.UTF-8 locale, which is fine for YottaDB. Remove LANG and LANGUAGE
varaibles, as these are not used by YottaDB.
- Remove clang, add gcc, as it's required by go for the tests. gcc must
have been implicitly added by other packages removed in the commit.
clang isn't needed.
- Remove vim, add nano instead.