Fix -Wimplicit-int, -Wformat and -Wpointer-to-int-cast warnings from offset.csh with gcc 14.2
Background
----------
* After upgrading to Ubuntu 24.10, an in-house system failed various tests that involved the use
  of `$gtm_tools/offset.csh`.

* An example test that failed is the `v60001/gtm7454` subtest. It had the following failure diff.

  ```diff
  > ##TEST_OUTPUT##/v60001_0/gtm7454/dse_cache_show.out
  > %YDB-E-CLIERR, Unrecognized option : OFFSET, value expected but not found
  > ##TEST_OUTPUT##/v60001_0/gtm7454/offset.out
  > OFFSET-E-SRCSTRUCTMISMATCH : Very likely that the c-structure isn't used in the c-source-file-name. Please give a valid input.
  ```

* Looking at offset.out, I noticed a lot of warnings.

  ```sh
  $ grep '\-W' /offset.out | wc -l
  519
  ```

* The first 5 lines had all the types of warnings that showed up.

  ```sh
  $ iconv -c -f UTF-8 offset.out | grep '\-W' | head -5
  /usr/library/V999_R203/inc/gdsbt.h:711:8: error: return type defaults to int [-Wimplicit-int]
  /usr/library/V999_R203/inc/gdsbt.h:715:26: warning: format %d expects argument of type int, but argument 2 has type long unsigned int [-Wformat=]
  /usr/library/V999_R203/inc/gdsbt.h:715:26: warning: format %x expects argument of type unsigned int, but argument 3 has type long unsigned int [-Wformat=]
  /usr/library/V999_R203/inc/gdsbt.h:708:49: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  /usr/library/V999_R203/inc/gdsbt.h:708:49: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  ```

Issues/Fixes
------------
There are various issues here.

* Notice the location of the error shows up as in `gdsbt.h` above. But at line 711 (`-Wimplicit-int`
  warning above) of that file, there is no `main()` function. But at line 711 of the C program that
  `sr_unix/offset.csh` generates, there is a `main()` function definition.

  Therefore, the C file name should not have been `gdsbt.h` but instead should have been the full path
  of the `offset.csh` generated C program.

  The fix is in `sr_unix/offset.csh` to filter out lines starting with `#` while generating the C program.
  This is because `gcc -E` (done in the previous step) generates those lines and those help the compiler
  issue the location of the error. But since we are now generating a new C program, those `#` marker
  lines will confuse stuff when we compile the generated C program into issuing misleading error messages.

* The `-Wformat` warnings are due to `sizeof()` returning a `long unsigned int` type but the format
  specifier `%d` implies a `int` type.

  This is fixed by changing `%d` and `%x` to `%ld` and `%lx` whenever they correspond to a `sizeof()`
  invocation in `sr_unix/offset.awk`.

* The `-Wpointer-to-int-cast` warnings are due to the `offsetof()` macro trying to type cast a pointer
  to `int`.

  This is fixed by inserting a `intptr_t` typecast in between in `sr_unix/offset.awk`.

* The `-Wimplicit-int` warning is because `main()` returns nothing.

  This is fixed by adding a `void` return type before `main()` in `sr_unix/offset.awk`.