Fix [-Werror,-Wstrict-prototypes] error in sr_unix/libyottadb.h when compiling with clang
* As part of YDBTest@0d51a044, installing plugins like YDBOcto etc. during `ydbinstall` was
  changed to use `clang` as the compiler in case `libyottadb.so` was built with CLANG + ASAN.

* After that change, it was noticed that the YDBGUI and YDBSodium plugins failed the install as
  follows.

  **YDBGUI**
  ```sh
  $ cat YDBGUI.err
  In file included from /tmp/tmp.RqX9D49GEX/YDBGUI_tmp/YDBGUI-master/build/_deps/ydbsodium-src/src/sodium_plugin.c:14:
  sudo_0/plugins/install/libyottadb.h:288:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    288 | typedef int             (*ydb_pointertofunc_t)();
        |                                               ^
        |                                                void
  sudo_0/plugins/install/libyottadb.h:289:39: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    289 | typedef void            (*ydb_funcptr_retvoid_t)();
        |                                                 ^
        |                                                  void
  sudo_0/plugins/install/libyottadb.h:347:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    347 | typedef uintptr_t       (*ydb_vplist_func)();           /* Indeterminate argument list for called variadic function */
        |                                           ^
        |                                            void
  ```

  **YDBSodium**
  ```sh
  $ cat YDBSodium.err
  In file included from /tmp/tmp.RqX9D49GEX/YDBSodium_tmp/YDBSodium-master/src/sodium_plugin.c:14:
  sudo_0/plugins/install/libyottadb.h:288:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    288 | typedef int             (*ydb_pointertofunc_t)();
        |                                               ^
        |                                                void
  sudo_0/plugins/install/libyottadb.h:289:39: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    289 | typedef void            (*ydb_funcptr_retvoid_t)();
        |                                                 ^
        |                                                  void
  sudo_0/plugins/install/libyottadb.h:347:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    347 | typedef uintptr_t       (*ydb_vplist_func)();           /* Indeterminate argument list for called variadic function */
        |                                           ^
        |                                            void
  3 errors generated.
  ```

* Both the failures are similar and point to a few longstanding empty prototype usages for a few function
  pointers in `sr_unix/libyottadb.h`.

* These errors are fixed in this commit by using `void` instead of an empty prototype.